// Central model registry — import from here for cleaner controller code
module.exports = {
  User:           require('./User'),
  Mentor:         require('./Mentor'),
  Profile:        require('./Profile'),
  Team:           require('./Team'),
  Booking:        require('./Booking'),
  Event:          require('./Event'),
  EventFeedback:  require('./EventFeedback'),
  EventRegistration: require('./EventRegistration'),
  Funding:        require('./Funding'),
  PitchEvent:     require('./PitchEvent'),
  PitchRegistration: require('./PitchRegistration'),
  PitchScore:     require('./PitchScore'),
  PitchVote:      require('./PitchVote'),
  PitchRoom:      require('./PitchRoom'),
  PitchDeck:      require('./PitchDeck'),
  DeckReview:     require('./DeckReview'),
  Connection:     require('./Connection'),
  Message:        require('./Message'),
  PrivateMessage: require('./PrivateMessage'),
  Notification:   require('./Notification'),
  Canvas:         require('./Canvas'),
  CanvasBoard:    require('./CanvasBoard'),
  CanvasComment:  require('./CanvasComment'),
  CanvasVersion:  require('./CanvasVersion'),
  Curriculum:     require('./Curriculum'),
  CurriculumProgress: require('./CurriculumProgress'),
  EmailLog:       require('./EmailLog'),
  EmailPreference: require('./EmailPreference'),
  // Module 3: Admin Panel & Verification System
  ProfileReport:  require('./ProfileReport'),
  FeaturedContent: require('./FeaturedContent'),
  // Module 1: Resource Library
  Resource:       require('./Resource'),
  Report:         require('./Report'),
};
